### ISSUE TITLE
open_in_new_tab/css/open_in_new_tab.css missing from pypi package

### ISSUE THREAD

**Issue by jmigual** [JakubAndrysek/mkdocs-open-in-new-tab#12]
I've installed the package using poetry: `poetry add mkdocs-open-in-new-tab` but when I try to build with the `add_icon: true` option it fails saying that it cannot find the `open_in_new_tab.css` file. I've checked the [file in Pypi](https://files.pythonhosted.org/packages/82/e4/268866f36a86f28d71939f1ae352eb623145f3befa7c52f0ddf0c4777a40/mkdocs_open_in_new_tab-1.0.7.tar.gz) and it is indeed missing.

**Comment by e4rthdog** [comment]
Did you find a workaround for this?

**Comment by jmigual** [comment]
Nope, for now I decided to not use the `add_icon: true` setting and it works.

**Comment by e4rthdog** [comment]
> Nope, for now I decided to not use the `add_icon: true` setting and it works.

I just added the css folder where it is expected to be found and it works. At least i will be able to compile it properly.

**Comment by JakubAndrysek** [comment]
Hi, I will fix it in the evening. Sorry for the trouble.

**Comment by JakubAndrysek** [comment]
Fixed urgently. 
Try the latest version: https://pypi.org/project/mkdocs-open-in-new-tab/1.0.8/

**Comment by JakubAndrysek** [comment]
Please let me know if it works. 
@e4rthdog  @jmigual 
Thank you.

**Comment by e4rthdog** [comment]
> Please let me know if it works. @e4rthdog @jmigual Thank you.

It works for me. Thank you!
