### ISSUE TITLE
Does not work with material navigation.instant

### ISSUE THREAD

**Issue by ptyork** [JakubAndrysek/mkdocs-open-in-new-tab#2]
The "navigation.instant" feature of the material theme breaks this plugin. It works on full page load (initial load, refresh, etc.) but not after navigating an internal link.

I assume using this feature just prevents the `DOMContentLoaded` event from firing during internal navigation. Perhaps there is another event that can be used to trigger your `*_new_window()` functions? I don't know enough about what is core MkDocs vs. Material for MkDocs to even know where to start looking for this. But maybe you do. ;)

**Comment by JakubAndrysek** [comment]
Hi, I have tried to fix it, but nothing works.
I run the JS script on page load, but it doesn't handle the page change.
If you have any ideas, please let me know.

My test code is here:
```js
window.addEventListener('popstate', function(event) {
    // Handle the page change here
    console.log("popstate: " + document.location + ", state: " + JSON.stringify(event.state));
});

window.addEventListener('hashchange', function(event) {
    // Handle the page change here
    console.log("hashchange: " + document.location + ", state: " + JSON.stringify(event.state));
});

window.addEventListener('change', function(event) {
    // Handle the page change here
    console.log("change: " + document.location + ", state: " + JSON.stringify(event.state));
});

window.addEventListener("DOMContentSwitch", function() {
    console.log("DOMContentSwitch" + document.location);
});

window.addEventListener("DOMContentLoaded", function() {
    console.log("DOMContentLoaded" + document.location);
});

window.addEventListener("change", function() {
    console.log("change" + document.location);
});
```

**Comment by JakubAndrysek** [comment]
Look at [mkdocs-charts-plugin](https://github.com/timvink/mkdocs-charts-plugin/blob/87789f5fe3a71d93fc9b1a97d9084ed666361e6f/mkdocs_charts_plugin/js/mkdocs-charts-plugin.js#L240)

**Comment by JakubAndrysek** [comment]
Add support for instant loading - MkDocs Material.

Thanks to [mkdocs_charts_plugin](https://github.com/timvink/mkdocs-charts-plugin/blob/87789f5fe3a71d93fc9b1a97d9084ed666361e6f/mkdocs_charts_plugin/js/mkdocs-charts-plugin.js#L238-L246) plugin that supports that feature.
